virtual_bookshelf/extensions/database/models.py
from decimal import Decimal

from sqlalchemy import Numeric, String
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    mapped_column,
)


class Base(DeclarativeBase, MappedAsDataclass):
    pass


class Book(Base):
    __tablename__ = 'book'
    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    title: Mapped[str] = mapped_column(String(250), unique=True)
    author: Mapped[str] = mapped_column(String(250))
    rating: Mapped[Decimal] = mapped_column(Numeric(precision=3, scale=1))

virtual_bookshelf/extensions/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import DecimalField, StringField, SubmitField
from wtforms.validators import InputRequired, NumberRange


class CustomDecimalField(DecimalField):
    def __init__(
        self, label=None, validators=None, places=..., rounding=None, **kwargs
    ):
        self.widget.step = kwargs.pop('step', 'Any')
        super().__init__(label, validators, places, rounding, **kwargs)


class AddBook(FlaskForm):
    book_title = StringField('Book Title', validators=[InputRequired()])
    book_author = StringField('Book Author', validators=[InputRequired()])
    book_rating = CustomDecimalField(
        'Book Rating',
        validators=[InputRequired(), NumberRange(min=0, max=10)],
        step='0.1',
    )
    submit_btn = SubmitField('Save')
    cancel_btn = SubmitField('Cancel')


class EditBook(AddBook):
    book_title = StringField('Book Title', render_kw={'readonly': True})
    book_author = StringField('Book Author', render_kw={'readonly': True})

virtual_bookshelf/forms.py
from typing import Any

from flask_wtf import FlaskForm
from wtforms.fields import DecimalField, StringField, SubmitField
from wtforms.validators import InputRequired, NumberRange


class CustomDecimalField(DecimalField):
    def __init__(
        self, label=None, validators=None, places=..., rounding=None, **kwargs
    ):
        self.widget.step = kwargs.pop('step', 'Any')
        super().__init__(label, validators, places, rounding, **kwargs)


class AddBook(FlaskForm):
    book_title = StringField('Book Title', validators=[InputRequired()])
    book_author = StringField('Book Author', validators=[InputRequired()])
    book_rating = CustomDecimalField(
        'Book Rating',
        validators=[InputRequired(), NumberRange(min=0, max=10)],
        step='0.1',
    )
    submit_btn = SubmitField('Save')
    cancel_btn = SubmitField('Cancel')


class EditBook(AddBook):
    book_title = StringField('Book Title', render_kw={'readonly': True})
    book_author = StringField('Book Author', render_kw={'readonly': True})

virtual_bookshelf/__init__.py
from flask import Flask

from virtual_bookshelf import config, views
from virtual_bookshelf.extensions import appearance, database


def create_app(**kwargs) -> Flask:
    app = Flask(__name__)

    config.init_app(app, **kwargs)
    database.init_app(app)
    views.init_app(app)
    appearance.init_app(app)

    return app

virtual_bookshelf/extensions/database/__init__.py
import click
from flask import Flask
from sqlalchemy import create_engine, delete, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import scoped_session, sessionmaker

from .models import Base

Session = scoped_session(sessionmaker(autoflush=False))


def init_db() -> None:
    Base.metadata.drop_all(Session.get_bind())
    Base.metadata.create_all(Session.get_bind())


def init_app(app: Flask) -> None:
    engine = create_engine(app.config['DATABASE_URI'])
    Session.configure(bind=engine)

    @app.teardown_appcontext
    def remove_session(exception=None) -> None:
        Session.remove()

    @click.command('init-db')
    def init_db_command():
        """Clear the existing data and create new tables."""
        init_db()
        click.echo('Initialized the database.')

    app.cli.add_command(init_db_command)

virtual_bookshelf/views.py
from flask import (
    Blueprint,
    Flask,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from sqlalchemy import delete, select
from sqlalchemy.exc import IntegrityError
from werkzeug.wrappers import Response

from virtual_bookshelf.database import Session
from virtual_bookshelf.database.models import Book

bp = Blueprint('bookshelf', __name__)


@bp.route('/')
def index() -> str:
    all_books = Session.scalars(select(Book)).all()
    return render_template('index.html', all_books=all_books)


@bp.route('/add', methods=['GET', 'POST'])
def add_book() -> str | Response:
    if request.method == 'POST':
        book_title = request.form['book-title']
        book = Book(
            title=book_title,
            author=request.form['book-author'],
            rating=float(request.form['rating']),
        )
        Session.add(book)
        try:
            Session.commit()
        except IntegrityError:
            flash(f'Book {book_title!a} is already registered.', 'error')
        else:
            return redirect(url_for('index'))

    return render_template('add.html')


@bp.route('/delete-all')
def delete_all() -> Response:
    Session.execute(delete(Book))
    Session.commit()
    return redirect(url_for('index'))


@bp.route('/delete/<int:id>')
def delete_book(id: int) -> Response:
    book = Session.get(Book, id)
    Session.delete(book)
    Session.commit()
    return redirect(url_for('index'))


@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_book(id: int) -> str | Response:
    book = Session.get(Book, id)
    if request.method == 'POST' and book:
        book.rating = float(request.form['rating'])
        Session.commit()
        return redirect(url_for('index'))

    return render_template('edit.html', book=book)


def init_app(app: Flask) -> Flask:
    app.register_blueprint(bp)
    app.add_url_rule('/', endpoint='index')
    return app

virtual_bookshelf/views/__init__.py
from flask import Flask

from .routes import bp


def init_app(app: Flask) -> Flask:
    app.register_blueprint(bp)
    app.add_url_rule('/', endpoint='index')
    return app

virtual_bookshelf/views/routes.py
from decimal import Decimal

from flask import Blueprint, abort, flash, redirect, render_template, url_for
from flask.typing import ResponseReturnValue

from virtual_bookshelf.extensions.database import (
    IntegrityError,
    Session,
    select,
)
from virtual_bookshelf.extensions.database.models import Book
from virtual_bookshelf.extensions.forms import AddBook, EditBook

bp = Blueprint('bookshelf', __name__)


def _convert_to_decimal(value: Decimal | None) -> Decimal:
    if value is None:
        return Decimal('NaN')

    return value


@bp.route('/')
def index() -> str:
    all_books = Session.scalars(select(Book)).all()
    return render_template('index.html', all_books=all_books)


@bp.route('/add', methods=['GET', 'POST'])
def add_book() -> ResponseReturnValue:
    form = AddBook()

    if form.validate_on_submit():
        book_title = form.book_title.data
        book = Book(
            title=book_title,
            author=form.book_author.data,
            rating=_convert_to_decimal(form.book_rating.data),
        )
        try:
            Session.add(book)
            Session.commit()
        except IntegrityError:
            flash(f'Book {book_title!a} is already registered.', 'danger')
        else:
            return redirect(url_for('index'))

    return render_template('add.html', form=form)


@bp.route('/delete/<int:id>')
def delete_book(id: int) -> ResponseReturnValue:
    book = Session.get(Book, id)
    Session.delete(book)
    Session.commit()
    return redirect(url_for('index'))


@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_book(id: int) -> ResponseReturnValue:
    book = Session.get(Book, id)
    if not book:
        abort(404)

    form = EditBook(
        data={'book_title': book.title, 'book_author': book.author}
    )

    if form.validate_on_submit():
        book.rating = _convert_to_decimal(form.book_rating.data)
        Session.commit()
        return redirect(url_for('index'))

    return render_template('edit.html', form=form, book=book)

virtual_bookshelf/templates/add.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <meta name="description" content="Add a new book to the virtual bookshelf.">
    <title>Add book - My Virtual Bookshelf</title>
{% endblock head %}
{% block content %}
<main class="container">
    <h1>Add new book</h1>
    {% include 'components/notifications.html' %}
    <form action="{{ url_for('bookshelf.add_book') }}" method="post" novalidate>
        {% if 'csrf_token' in form %}
            {{ form.csrf_token }}
        {% endif %}
        {{ render_field(form.book_title) }}
        {{ render_field(form.book_author) }}
        {{ render_field(form.book_rating) }}
        {{ render_field(form.submit_btn, button_style='dark') }}
        <a class="btn btn-dark btn-md" href="{{ url_for('index') }}">Cancel</a>
    </form>
</main>
{% endblock content %}

virtual_bookshelf/templates/base.html
{% from 'bootstrap5/utils.html' import render_static %}
{% from 'bootstrap5/form.html' import render_field %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Igor Ferreira">
        {% block styles %}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
            {{ bootstrap.load_css() }}
            {{ render_static('css', 'style.css') }}
        {% endblock styles %}
        {% endblock head %}
    </head>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

virtual_bookshelf/templates/components/notifications.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
    <ul class="error-list list-group">
    {% for category, message in messages %}
        <li class="list-group-item list-group-item-{{ category }}">
            <strong>{{ message }}</strong>
        </li>
    {% endfor %}
    </ul>
{% endif %}
{% endwith %}

virtual_bookshelf/templates/edit.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <meta name="description" content="Edit data for a specific book.">
    <title>Edit book data - My Virtual Bookshelf</title>
{% endblock head %}
{% block content %}
<main class="container">
    <h1>Edit book data</h1>
    <form action="{{ url_for('bookshelf.edit_book', id=book.id) }}" method="post" novalidate>
        {% if 'csrf_token' in form %}
            {{ form.csrf_token }}
        {% endif %}
        {{ render_field(form.book_title) }}
        {{ render_field(form.book_author) }}
        {{ render_field(form.book_rating) }}
        {{ render_field(form.submit_btn, button_style='dark') }}
        <a class="btn btn-dark btn-md" href="{{ url_for('index') }}">Cancel</a>
    </form>
</main>
{% endblock content %}

virtual_bookshelf/templates/index.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <meta name="description" content="A virtual bookshelf.">
    <title>My Virtual Bookshelf</title>
{% endblock head %}
{% block content %}
    <main class="container">
        <h1>My Virtual Bookshelf</h1>
        <a href="{{ url_for('bookshelf.add_book') }}" class="btn btn-dark">New book</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Book Title</th>
                    <th scope="col">Book Author</th>
                    <th scope="col">Rating</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for book in all_books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.rating }}</td>
                    <td>
                        <a
                            class="icon-link" 
                            href="{{ url_for('bookshelf.edit_book', id=book.id) }}" 
                            title="Edit book data"
                        >
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <a 
                            class="icon-link" 
                            href="{{ url_for('bookshelf.delete_book', id=book.id) }}" 
                            title="Remove book"
                        >
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock content %} 